"use client";

import React from "react";
import type { RecentReportItem } from "../types/overview.types";

interface RecentReportsTableProps {
  reports: RecentReportItem[];
  onDownload: (report: RecentReportItem) => void;
}

export const RecentReportsTable: React.FC<RecentReportsTableProps> = ({
  reports,
  onDownload,
}) => {
  return (
    <div className="space-y-3.5">
      <h2 className="text-base font-bold text-foreground">
        Recently Generated Reports
      </h2>

      <div className="w-full overflow-x-auto rounded-xl border border-border/80 bg-card shadow-soft">
        <table className="w-full text-left border-collapse min-w-[850px]">
          <thead>
            <tr className="border-b border-border/80 bg-muted/30 text-[11px] font-bold text-muted-foreground uppercase tracking-wider">
              <th className="py-3.5 px-4">REPORT NAME</th>
              <th className="py-3.5 px-4">CATEGORY</th>
              <th className="py-3.5 px-4">GENERATED BY</th>
              <th className="py-3.5 px-4">DATE</th>
              <th className="py-3.5 px-4">STATUS</th>
              <th className="py-3.5 px-4 text-right">ACTIONS</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border/60 text-xs">
            {reports.map((report) => (
              <tr
                key={report.id}
                className="hover:bg-muted/30 transition-colors"
              >
                {/* REPORT NAME */}
                <td className="py-4 px-4 font-bold text-foreground whitespace-nowrap">
                  {report.name}
                </td>

                {/* CATEGORY */}
                <td className="py-4 px-4 whitespace-nowrap">
                  <span
                    className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-[11px] font-semibold border ${report.categoryColor}`}
                  >
                    {report.category}
                  </span>
                </td>

                {/* GENERATED BY */}
                <td className="py-4 px-4 text-muted-foreground whitespace-nowrap font-medium">
                  {report.generatedBy}
                </td>

                {/* DATE */}
                <td className="py-4 px-4 text-muted-foreground whitespace-nowrap">
                  {report.date}
                </td>

                {/* STATUS */}
                <td className="py-4 px-4 whitespace-nowrap">
                  {report.status === "Ready" ? (
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-secondary/10 text-secondary border border-secondary/20">
                      Ready
                    </span>
                  ) : (
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-amber-500/10 text-amber-600 border border-amber-500/20">
                      Processing
                    </span>
                  )}
                </td>

                {/* ACTIONS */}
                <td className="py-4 px-4 text-right whitespace-nowrap space-x-3">
                  {report.status === "Ready" ? (
                    <>
                      <button
                        type="button"
                        onClick={() => onDownload(report)}
                        className="text-primary font-bold hover:underline cursor-pointer"
                      >
                        View
                      </button>
                      <button
                        type="button"
                        onClick={() => onDownload(report)}
                        className="text-muted-foreground font-semibold hover:text-foreground cursor-pointer"
                      >
                        Download
                      </button>
                    </>
                  ) : (
                    <span className="text-muted-foreground italic">
                      Pending...
                    </span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};
