import { z } from "zod";

export const bookingTypeSettingsSchema = z.object({
  id: z.string(),
  name: z.string().trim().min(2, "Enter a booking type name."),
  description: z.string().trim().min(2, "Enter a description."),
  enabled: z.boolean(),
  commissionPercent: z.number().min(0).max(100),
  requirements: z.string().trim().min(2, "Enter the booking requirements."),
});

export const bookingsSettingsSchema = z
  .object({
    allowBookings: z.boolean(),
    confirmation: z.boolean(),
    cancellation: z.boolean(),
    rescheduling: z.boolean(),
    hostAcceptance: z.boolean(),
    autoConfirm: z.boolean(),
    bookingTypes: z.array(bookingTypeSettingsSchema),
    leadHours: z.enum(["12", "24", "48"]),
    advanceDays: z.enum(["30", "60", "90"]),
    eventDetails: z.boolean(),
    eventDate: z.boolean(),
    eventLocation: z.boolean(),
    guestCount: z.boolean(),
    serviceDetails: z.boolean(),
    customerCancellation: z.boolean(),
    hostCancellation: z.boolean(),
    cancellationDeadlineHours: z.number().int().min(0),
    cancellationFee: z.number().min(0),
    cancellationCurrency: z.enum(["NGN", "USD", "GBP"]),
    refundPercent: z.number().min(0).max(100),
    policyRescheduling: z.boolean(),
    reschedulingDeadlineHours: z.number().int().min(0),
    groupsEnabled: z.boolean(),
    groupCreation: z.boolean(),
    adminGroupCreation: z.boolean(),
    leaderManageMembers: z.boolean(),
    leaderInvite: z.boolean(),
    leaderRequired: z.boolean(),
    groupCreationApproval: z.boolean(),
    memberRemoval: z.boolean(),
    groupBookings: z.boolean(),
    groupLeaderApproval: z.boolean(),
    groupAdminApproval: z.boolean(),
    memberBookingRequests: z.boolean(),
    leaderConfirmBooking: z.boolean(),
    groupCancellation: z.boolean(),
    groupRescheduling: z.boolean(),
    minGroupSize: z.number().int().min(1),
    maxGroupSize: z.number().int().min(1),
    maxGroupsPerUser: z.number().int().min(1),
    maxBookingMembers: z.number().int().min(1),
    automaticAssignment: z.boolean(),
    reassignmentAfterConfirmation: z.boolean(),
    adminReassignment: z.boolean(),
    reassignmentApproval: z.boolean(),
    customerReassignment: z.boolean(),
    expirePending: z.boolean(),
    expirationHours: z.enum(["12", "24", "48"]),
    notifyUser: z.boolean(),
    notifyHost: z.boolean(),
  })
  .refine((value) => value.maxGroupSize >= value.minGroupSize, {
    path: ["maxGroupSize"],
    message: "Maximum group size must be at least the minimum.",
  });
